#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""patch_target_schema.py — vendor a LOCAL PATCH of the OHDSI GIS target schema.

Copies monarch-initiative/linkml-ohdsi-gis-extension-envar (#27) and comments
out `identifier: true` on eight ExternalExposure FK / concept-id slots. In
LinkML `identifier: true` implies required; OMOP treats these as nullable FKs
and 0-for-unmapped concept_ids, so the upstream marking rejects otherwise-valid
external_exposure rows. TEMPORARY until fixed upstream — do not treat the
output as canonical.

Usage:
    uv run --script patch_target_schema.py /path/to/linkml_ohdsi_gis_extension_envar.yaml
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

RELAX = {
    "location_id",  # real FK, filled by the person->Location join (follow-on)
    "exposure_concept_id", "exposure_type_concept_id",
    "exposure_relationship_concept_id", "exposure_source_concept_id",
    "operator_concept_id", "value_as_concept_id", "unit_concept_id",
}
HEADER = (
    "# ─────────────────────────────────────────────────────────────────────────\n"
    "# LOCAL PATCH — DO NOT treat as canonical. Generated by patch_target_schema.py.\n"
    "# Vendored copy of monarch-initiative/linkml-ohdsi-gis-extension-envar (#27)\n"
    "# with `identifier: true` commented out on 8 ExternalExposure FK/concept slots.\n"
    "# `identifier: true` implies required in LinkML; OMOP treats these as nullable\n"
    "# FKs / 0-for-unmapped concepts, so the upstream marking rejects valid rows.\n"
    "# Temporary until fixed upstream.\n"
    "# ─────────────────────────────────────────────────────────────────────────\n"
)
OUT = Path("vendor/linkml_ohdsi_gis_extension_envar.local-patch.yaml")


def main() -> int:
    src = Path(sys.argv[1]).read_text().splitlines()
    slot_hdr = re.compile(r"^  ([a-z_]+):\s*$")
    cur, patched, out = None, 0, []
    for ln in src:
        m = slot_hdr.match(ln)
        if m:
            cur = m.group(1)
        if cur in RELAX and ln.strip() == "identifier: true":
            out.append(ln.replace("identifier: true", "# identifier: true  # LOCAL PATCH (see header)"))
            patched += 1
            continue
        out.append(ln)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEADER + "\n".join(out) + "\n")
    print(f"patched {patched} identifier lines -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
